### ISSUE TITLE
Feature - Add Font Toggle to the website

### ISSUE THREAD

**Issue by CollinHerber** [D2R-Reimagined/d2r-reimagined-website#5]
Some people no like d2 font
Make more font option

**Comment by loreggia** [comment]
First of all, thanks for creating the mod, having a blast so far! The website is really nice, but I'm kinda in the same boat concerning the font. I think one of the main problems is that the lower case "t" looks like a plus, which makes it kinda hard to read. As a first step, instead of having to implement a font toggle, you could also replace the current font with the actual D2R font (it is stored in the extracted game files at "Data/hd/ui/fonts/exocetblizzardot-medium.otf"), which in my opinion is way more readable and keeps the D2 feel.
(Not sure about the legality of this though, but probably wouldn't be a problem as long as the mod/website keeps being non-commercial..)

**Comment by loreggia** [comment]
Comparison:
![current-font](https://github.com/user-attachments/assets/31f1877d-4bf5-4769-b14b-94d89bdc6a3c)
![d2r-font](https://github.com/user-attachments/assets/a7a69577-8cf1-4974-bd70-4d9a1177609c)

**Comment by CollinHerber** [comment]
> First of all, thanks for creating the mod, having a blast so far! The website is really nice, but I'm kinda in the same boat concerning the font. I think one of the main problems is that the lower case "t" looks like a plus, which makes it kinda hard to read. As a first step, instead of having to implement a font toggle, you could also replace the current font with the actual D2R font (it is stored in the extracted game files at "Data/hd/ui/fonts/exocetblizzardot-medium.otf"), which in my opinion is way more readable and keeps the D2 feel. (Not sure about the legality of this though, but probably wouldn't be a problem as long as the mod/website keeps being non-commercial..) I could do a pull request with that font if you'd like.

I'd  be happy to accept a PR for the font. I'd like it to be a toggle however. So maybe something in the top-right to toggle between fonts?

**Comment by CollinHerber** [comment]
Thanks for this! Reach out to me on discord for your role
